-- MySQL Script generated by MySQL Workbench
-- 08/24/14 17:55:46
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bored
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bored` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bored` ;

-- -----------------------------------------------------
-- Table `bored`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `horario2f` VARCHAR(45) NOT NULL,
  `horario3f` VARCHAR(45) NOT NULL,
  `horario4f` VARCHAR(45) NOT NULL,
  `horario5f` VARCHAR(45) NOT NULL,
  `horario6f` VARCHAR(45) NOT NULL,
  `horariosabado` VARCHAR(45) NOT NULL,
  `horariodomingo` VARCHAR(45) NOT NULL,
  `horarioferiado` VARCHAR(45) NOT NULL,
  `horariodiadefecho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhorario`),
  UNIQUE INDEX `idhorario_UNIQUE` (`idhorario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`Pais` (
  `PaisNome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PaisNome`),
  UNIQUE INDEX `PaisNome_UNIQUE` (`PaisNome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`actividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`actividade` (
  `idactividade` INT NOT NULL AUTO_INCREMENT,
  `actividadenome` VARCHAR(100) NOT NULL,
  `actividademorada` VARCHAR(100) NOT NULL,
  `actividadegps` VARCHAR(50) NULL,
  `actividadepais` VARCHAR(50) NOT NULL,
  `actividadefoto` VARCHAR(100) NULL,
  `horario_idhorario` INT NOT NULL,
  `Pais_idPais` INT NOT NULL,
  `Pais_PaisNome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idactividade`, `horario_idhorario`),
  UNIQUE INDEX `idactividade_UNIQUE` (`idactividade` ASC),
  INDEX `fk_actividade_horario1_idx` (`horario_idhorario` ASC),
  INDEX `fk_actividade_Pais1_idx` (`Pais_idPais` ASC, `Pais_PaisNome` ASC),
  CONSTRAINT `fk_actividade_horario1`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `bored`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividade_Pais1`
    FOREIGN KEY (`Pais_PaisNome`)
    REFERENCES `bored`.`Pais` (`PaisNome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`eventoTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`eventoTipo` (
  `ideventoTipo` INT NOT NULL AUTO_INCREMENT,
  `eventoTipoNome` VARCHAR(50) NOT NULL,
  `eventoTipoArlivre` TINYINT(1) NOT NULL,
  `eventoTipoGratis` TINYINT(1) NOT NULL,
  `eventoTipoPermiteCriancas` TINYINT(1) NOT NULL,
  UNIQUE INDEX `ideventoTipo_UNIQUE` (`ideventoTipo` ASC),
  PRIMARY KEY (`ideventoTipo`),
  UNIQUE INDEX `eventoTipoNome_UNIQUE` (`eventoTipoNome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`evento` (
  `actividade_idactividade` INT NOT NULL,
  `eventoTipo_ideventoTipo` INT NOT NULL,
  `eventoTipodata` DATETIME NOT NULL,
  PRIMARY KEY (`actividade_idactividade`),
  INDEX `fk_evento_eventoTipo1_idx` (`eventoTipo_ideventoTipo` ASC),
  CONSTRAINT `fk_evento_actividade`
    FOREIGN KEY (`actividade_idactividade`)
    REFERENCES `bored`.`actividade` (`idactividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_eventoTipo1`
    FOREIGN KEY (`eventoTipo_ideventoTipo`)
    REFERENCES `bored`.`eventoTipo` (`ideventoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`pontoTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`pontoTipo` (
  `idpontoTipo` INT NOT NULL AUTO_INCREMENT,
  `pontoTipoNome` VARCHAR(50) NOT NULL,
  `pontoTipoApenasNocturno` TINYINT(1) NOT NULL,
  `pontoTipoPermiteCriancas` TINYINT(1) NOT NULL,
  `pontoTipoArLivre` TINYINT(1) NOT NULL,
  `pontoTipoGratis` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idpontoTipo`),
  UNIQUE INDEX `pontoTipoNome_UNIQUE` (`pontoTipoNome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`ponto` (
  `actividade_idactividade` INT NOT NULL,
  `pontoTipo_idpontoTipo` INT NOT NULL,
  PRIMARY KEY (`actividade_idactividade`),
  INDEX `fk_ponto_actividade1_idx` (`actividade_idactividade` ASC),
  INDEX `fk_ponto_pontoTipo1_idx` (`pontoTipo_idpontoTipo` ASC),
  CONSTRAINT `fk_ponto_actividade1`
    FOREIGN KEY (`actividade_idactividade`)
    REFERENCES `bored`.`actividade` (`idactividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ponto_pontoTipo1`
    FOREIGN KEY (`pontoTipo_idpontoTipo`)
    REFERENCES `bored`.`pontoTipo` (`idpontoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`netTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`netTipo` (
  `idnetTipo` INT NOT NULL AUTO_INCREMENT,
  `netTipoNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnetTipo`),
  UNIQUE INDEX `idnetTipo_UNIQUE` (`idnetTipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bored`.`net`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bored`.`net` (
  `actividade_idactividade` INT NOT NULL,
  `netTipo_idnetTipo` INT NOT NULL,
  PRIMARY KEY (`actividade_idactividade`),
  INDEX `fk_net_actividade1_idx` (`actividade_idactividade` ASC),
  INDEX `fk_net_netTipo1_idx` (`netTipo_idnetTipo` ASC),
  CONSTRAINT `fk_net_actividade1`
    FOREIGN KEY (`actividade_idactividade`)
    REFERENCES `bored`.`actividade` (`idactividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_net_netTipo1`
    FOREIGN KEY (`netTipo_idnetTipo`)
    REFERENCES `bored`.`netTipo` (`idnetTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
